#!/bin/bash

if [[ $EUID != 0 ]]
then
    echo "Tienes de ser root"
    echo ""
    exit
fi

while true
do
hora=$(date +"%H:%M")

nombreservidor=$(hostname)
ipservidor=$(hostname -I)
memoriaservidort=$(free -m -h | grep "Mem" | awk '{ print $2}')
memoriaservidoru=$(free -m -h | grep "Mem" | awk '{ print $3}')
memoriaservidord=$(free -m -h | grep "Mem" | awk '{ print $7}')

redservidor=$(netstat -atupan | grep ESTABLISHED)

cpuservidoru=$(mpstat -P ALL | grep "all" | awk '{ print $3"%"}')
cpuservidors=$(mpstat -P ALL | grep "all" | awk '{ print $5"%"}')
cpuservidord=$(mpstat -P ALL | grep "all" | awk '{ print $12"%"}')

ipdocker1=$(docker exec register hostname -I)
nombredocker1=$(docker exec register hostname )
d1memoriaservidort=$(docker exec register free -m -h | grep "Mem" | awk '{ print $2}')
d1memoriaservidoru=$(docker exec register free -m -h | grep "Mem" | awk '{ print $3}')
d1memoriaservidord=$(docker exec register free -m -h | grep "Mem" | awk '{ print $7}')

d1redservidor=$(docker exec register netstat -atupan | grep ESTABLISHED)

d1cpuservidoru=$(docker exec register mpstat -P ALL | grep "all" | awk '{ print $3"%"}')
d1cpuservidors=$(docker exec register mpstat -P ALL | grep "all" | awk '{ print $5"%"}')
d1cpuservidord=$(docker exec register mpstat -P ALL | grep "all" | awk '{ print $12"%"}')

ipdocker2=$(docker exec login hostname -I)
nombredocker2=$(docker exec login hostname )
d2memoriaservidort=$(docker exec login free -m -h | grep "Mem" | awk '{ print $2}')
d2memoriaservidoru=$(docker exec login free -m -h | grep "Mem" | awk '{ print $3}')
d2memoriaservidord=$(docker exec login free -m -h | grep "Mem" | awk '{ print $7}')

d2redservidor=$(docker exec login netstat -atupan | grep ESTABLISHED)

d2cpuservidoru=$(docker exec login mpstat -P ALL | grep "all" | awk '{ print $3"%"}')
d2cpuservidors=$(docker exec login mpstat -P ALL | grep "all" | awk '{ print $5"%"}')
d2cpuservidord=$(docker exec login mpstat -P ALL | grep "all" | awk '{ print $12"%"}')

ipdocker3=$(docker exec mariadb hostname -I)
nombredocker3=$(docker exec mariadb hostname )
d3memoriaservidort=$(docker exec mariadb free -m -h | grep "Mem" | awk '{ print $2}')
d3memoriaservidoru=$(docker exec mariadb free -m -h | grep "Mem" | awk '{ print $3}')
d3memoriaservidord=$(docker exec mariadb free -m -h | grep "Mem" | awk '{ print $7}')

d3redservidor=$(docker exec mariadb netstat -atupan | grep ESTABLISHED)

d3cpuservidoru=$(docker exec mariadb mpstat -P ALL | grep "all" | awk '{ print $3"%"}')
d3cpuservidors=$(docker exec mariadb mpstat -P ALL | grep "all" | awk '{ print $5"%"}')
d3cpuservidord=$(docker exec mariadb mpstat -P ALL | grep "all" | awk '{ print $12"%"}')


echo "
<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Monitorizacion</title>
    <meta http-equiv="refresh" content="7">

<style>
    body{
    background-color: #3D69EE;
    background-attachment: fixed;
    background-size: cover;
    background-image: url(https://img.freepik.com/foto-gratis/fondos-hexadecimales-oscuros-redes_23-2149755769.jpg?w=1060&t=st=1678278928~exp=1678279528~hmac=81cf06dde2cddf13bb2fb13660ab497fb2a29ba4506e6b6fa0562f45c28711af);
    }

  #heading{
    margin-top: 3%;
    margin-bottom: 10%;
    text-align: center;
    font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
    letter-spacing: 0px;
    color: #ffffff;
    text-shadow: 1px 5px 15px rgba(0, 0, 0, 0.521);
    background-color: rgba(240, 248, 255, 0.422);
    border-radius: 15px;
    }

    #content{
      margin-top: -120px;


    }
    h2{
      color: white;
      margin-top: 10px;
    }
    summary::marker{
      color: transparent;
    }
    #columnas{
      background-color: rgba(240, 248, 255, 0.422);

    }
</style>

</head>
<body>
<div class="container" id="heading">
    <div class="row align-items-center">
        <div class="col-3">
            <h5>Monitorizacion</h5>
        </div>
    <div class="col-6">
        <h1 class="title">Monitorizacion</h1>
    </div>
    <div class="col-3">
        <h5>$hora</h5>
    </div>
</div>
</div>

<div class="container" id="content">
      <div class="row">
          <div class="col text-center" id="columnas"><h2>Servidor</h2><summary>$ipservidor - $nombreservidor</summary></br>

            <div class="row">
                <div class="col text-center"><h4>RAM Total</h4>
                  <div>$memoriaservidort</div>
                </div>
                <div class="col text-center"><h4>RAM Usada</h4>
                  <div>$memoriaservidoru</div>
                </div>
                <div class="col text-center"><h4>RAM Disponible</h4>
                 <div>$memoriaservidord</div>
                </div>
            </div>

            <div class="row">
              <div class="col text-center"><h4>Red</h4>
                <div>$redservidor</div>
              </div>
           </div>

          <div class="row">
            <div class="col text-center"><h4>CPU Usr</h4>
              <div>$cpuservidoru</div>
            </div>
            <div class="col text-center"><h4>CPU Sys</h4>
              <div>$cpuservidors</div>
            </div>
            <div class="col text-center"><h4>CPU Disponible</h4>
             <div>$cpuservidord</div>
          </div>
          </div>

        </div>

        <div class="col text-center" id="columnas"><h2>Docker Registro</h2><summary>$ipdocker1 - $nombredocker1</summary></br>

          <div class="row">
            <div class="col text-center"><h4>RAM Total</h4>
              <div>$d1memoriaservidort</div>
            </div>
            <div class="col text-center"><h4>RAM Usada</h4>
              <div>$d1memoriaservidoru</div>
            </div>
            <div class="col text-center"><h4>RAM Disponible</h4>
             <div>$d1memoriaservidord</div>
            </div>
        </div>

        <div class="row">
          <div class="col text-center"><h4>Red</h4>
            <div>$d1redservidor</div>
          </div>
       </div>

       <div class="row">
        <div class="col text-center"><h4>CPU Usr</h4>
          <div>$d1cpuservidoru</div>
        </div>
        <div class="col text-center"><h4>CPU Sys</h4>
          <div>$d1cpuservidors</div>
        </div>
        <div class="col text-center"><h4>CPU Disponible</h4>
         <div>$d1cpuservidord</div>
      </div>
      </div>

        </div>
      </div>


        <div class="row">

            <div class="col text-center" id="columnas"><h2>Docker Login</h2><summary>$ipdocker2 - $nombredocker2</summary></br>

              <div class="row">
                <div class="col text-center"><h4>RAM Total</h4>
                  <div>$d2memoriaservidort</div>
                </div>
                <div class="col text-center"><h4>RAM Usada</h4>
                  <div>$d2memoriaservidoru</div>
                </div>
                <div class="col text-center"><h4>RAM Disponible</h4>
                 <div>$d2memoriaservidord</div>
                </div>

                <div class="row">
                  <div class="col text-center"><h4>Red</h4>
                    <div>$d2redservidor</div>
                  </div>
               </div>

               <div class="row">
                <div class="col text-center"><h4>CPU Usr</h4>
                  <div>$d2cpuservidoru</div>
                </div>
                <div class="col text-center"><h4>CPU Sys</h4>
                  <div>$d2cpuservidors</div>
                </div>
                <div class="col text-center"><h4>CPU Disponible</h4>
                 <div>$d2cpuservidord</div>
              </div>
              </div>

            </div>
            </div>

            <div class="col text-center" id="columnas"><h2>Docker Mariadb</h2><summary>$ipdocker3 - $nombredocker3</summary></br>

              <div class="row">
                <div class="col text-center"><h4>RAM Total</h4>
                  <div>$d3memoriaservidort</div>
                </div>
                <div class="col text-center"><h4>RAM Usada</h4>
                  <div>$d3memoriaservidoru</div>
                </div>
                <div class="col text-center"><h4>RAM Disponible</h4>
                 <div>$d3memoriaservidord</div>
                </div>
            </div>

            <div class="row">
              <div class="col text-center"><h4>Red</h4>
                <div>$d3redservidor</div>
              </div>
           </div>

           <div class="row">
            <div class="col text-center"><h4>CPU Usr</h4>
              <div>$d3cpuservidoru</div>
            </div>
            <div class="col text-center"><h4>CPU Sys</h4>
              <div>$d3cpuservidors</div>
            </div>
            <div class="col text-center"><h4>CPU Disponible</h4>
             <div>$d3cpuservidord</div>
          </div>
          </div>

            </div>
        </div>
</div>
</body>
</html>" > /var/www/html/index.html
done
